package netease

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"testing"
)

// These expected bytes were generated by executing the original archive's
// TypeScript with a fixed IV, key selector, and random suffix.
func TestOriginalNethardWireAndTokenFixtures(t *testing.T) {
	data, err := os.ReadFile("testdata/nethard_vectors.json")
	if err != nil {
		t.Fatal(err)
	}
	var vectors struct {
		HTTP struct {
			Plain    string `json:"plain"`
			IVHex    string `json:"iv_hex"`
			KeyIndex int    `json:"key_index"`
			Suffix   string `json:"suffix"`
			Expected string `json:"expected"`
		} `json:"http"`
		Tokens     []struct{ Path, Body, Token, Expected string } `json:"tokens"`
		Signatures []struct{ Message, Expected string }           `json:"signatures"`
	}
	if err := json.Unmarshal(data, &vectors); err != nil {
		t.Fatal(err)
	}
	iv, err := hex.DecodeString(vectors.HTTP.IVHex)
	if err != nil {
		t.Fatal(err)
	}
	wire, err := encryptHTTPRequestFixed([]byte(vectors.HTTP.Plain), iv, vectors.HTTP.KeyIndex, []byte(vectors.HTTP.Suffix))
	if err != nil {
		t.Fatal(err)
	}
	if wire != vectors.HTTP.Expected {
		t.Fatalf("V4 request differs from original TypeScript: %s", wire)
	}
	for _, vector := range vectors.Tokens {
		if got := DynamicToken(vector.Path, vector.Body, vector.Token); got != vector.Expected {
			t.Errorf("signature differs from original TypeScript for %s: %s", vector.Path, got)
		}
	}
	for _, vector := range vectors.Signatures {
		if got := CountSignBase64(vector.Message); got != vector.Expected {
			t.Errorf("login signature differs from original TypeScript: %s", got)
		}
	}
}

func TestNethardLoginParameters(t *testing.T) {
	sauth := json.RawMessage(`{"sdkuid":"fixture","sessionid":"fixture","app_channel":"netease","udid":"fixture-device"}`)
	saData, err := buildSAData(sauth)
	if err != nil {
		t.Fatal(err)
	}
	var device map[string]any
	if err := json.Unmarshal([]byte(saData), &device); err != nil {
		t.Fatal(err)
	}
	if device["first_udid"] != "fixture-device" || device["udid"] != "fixture-device" || device["start_type"] != "defualt" {
		t.Fatalf("default device fields differ from source: %#v", device)
	}
	body, err := buildPEAuthPlain("00000000-0000-5000-8000-000000000000", saData, sauth)
	if err != nil {
		t.Fatal(err)
	}
	var login map[string]any
	if err := json.Unmarshal(body, &login); err != nil {
		t.Fatal(err)
	}
	if login["pay_channel"] != "dashen_cloudgame" || login["sa_data"] != saData {
		t.Fatalf("login parameters differ from source: %#v", login)
	}
}
