'use strict';
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let admin=sessionStorage.getItem('n2a-admin')||'',chatController=null,refreshTimer=null;
const titles={overview:['概览','服务概览'],accounts:['账号池','账号池'],keys:['API 密钥','API 密钥'],playground:['对话测试','对话测试'],logs:['请求记录','请求记录']};
const statusNames={unverified:['待检查','neutral'],ready:['可用','green'],busy:['使用中','orange'],disabled:['已停用','neutral'],cooldown:['冷却中','orange'],login_required:['需更新 Cookie','red'],error:['请求失败','red']};
let toastTimer;
function toast(message,error=false){$('toast').textContent=message;$('toast').className='toast'+(error?' error':'');$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4500)}
async function api(path,options={}){const response=await fetch(path,{...options,headers:{'Authorization':'Bearer '+admin,'Content-Type':'application/json',...options.headers}});const body=await response.json();if(!response.ok){if(response.status===401)logout();throw new Error(body.error?.message||'请求失败')}return body}
function page(name){if(!titles[name])return;document.querySelectorAll('.page').forEach(el=>el.hidden=el.id!=='page-'+name);document.querySelectorAll('[data-page]').forEach(el=>el.classList.toggle('active',el.dataset.page===name));$('breadcrumb').textContent=titles[name][0];$('page-title').textContent=titles[name][1]}
function date(value){if(!value||String(value).startsWith('0001'))return '—';return new Date(value).toLocaleString('zh-CN',{hour12:false})}
function badge(status){const [text,color]=statusNames[status]||['未知','neutral'];return `<span class="badge ${color}">${text}</span>`}
async function refresh(){const [overview,accounts,keys,logs]=await Promise.all([api('/admin/overview'),api('/admin/accounts'),api('/admin/keys'),api('/admin/logs')]);$('stat-total').textContent=overview.accounts;$('stat-ready').textContent=overview.available;$('stat-busy').textContent=overview.busy+' 个账号正在使用';$('stat-success').textContent=overview.successful_requests;$('stat-failed').textContent=overview.failed_attempts;$('version').textContent='v'+overview.version;$('base-url').textContent=location.origin+'/v1';
 $('accounts-empty').hidden=accounts.length>0;
 $('account-rows').innerHTML=accounts.map(a=>`<tr><td>${esc(a.name)}<small>${esc(a.channel||"netease")} · ${esc(a.sdk_uid||"等待检查")}</small>${a.last_error?`<small class="danger">${esc(a.last_error)}</small>`:''}</td><td>${badge(a.status)}${a.status==='cooldown'?`<small>至 ${esc(date(a.cooldown_until))}</small>`:''}</td><td>${a.success_count} <span class="muted">/ ${a.failure_count}</span></td><td>${a.last_latency_ms?esc((a.last_latency_ms/1000).toFixed(1))+'s':'—'}</td><td><button data-action="check" data-id="${esc(a.id)}" ${a.busy?'disabled':''}>检查</button><button data-action="toggle" data-enabled="${!a.enabled}" data-id="${esc(a.id)}" ${a.busy?'disabled':''}>${a.enabled?'停用':'启用'}</button><button class="danger" data-action="delete" data-id="${esc(a.id)}" ${a.busy?'disabled':''}>删除</button></td></tr>`).join('');
 $('key-rows').innerHTML=keys.map(k=>`<tr><td>${esc(k.name)}</td><td class="mono">${esc(k.prefix)}</td><td><span class="badge ${k.enabled?'green':'neutral'}">${k.enabled?'启用':'已撤销'}</span></td><td>${esc(date(k.created_at))}</td><td><button data-revoke="${esc(k.id)}" class="danger" ${k.enabled?'':'disabled'}>撤销</button></td></tr>`).join('');
 $('logs-empty').hidden=logs.length>0;$('log-rows').innerHTML=logs.map(l=>`<tr><td>${esc(date(l.at))}</td><td>${esc(l.account_name)}</td><td><span class="badge ${l.ok?'green':'red'}">${l.ok?'成功':'失败'}</span>${l.error?`<small>${esc(l.error)}</small>`:''}</td><td>${esc((l.latency_ms/1000).toFixed(1))}s</td><td class="mono">${esc(l.id)}</td></tr>`).join('')}
async function show(){await refresh();$('login-screen').hidden=true;$('shell').hidden=false;clearInterval(refreshTimer);refreshTimer=setInterval(()=>{if(!document.hidden)refresh().catch(()=>{})},10000)}
function logout(){admin='';sessionStorage.removeItem('n2a-admin');sessionStorage.removeItem('n2a-api');$('chat-key').value='';$('admin-key').value='';$('shell').hidden=true;$('login-screen').hidden=false;clearInterval(refreshTimer);chatController?.abort()}
$('login-form').addEventListener('submit',async e=>{e.preventDefault();admin=$('admin-key').value.trim();$('login-error').textContent='';const button=e.submitter;button.disabled=true;try{await show();sessionStorage.setItem('n2a-admin',admin);$('admin-key').value=''}catch(err){$('login-error').textContent=err.message}finally{button.disabled=false}});
$('logout').addEventListener('click',logout);
document.querySelectorAll('[data-page]').forEach(button=>button.addEventListener('click',()=>page(button.dataset.page)));
document.querySelectorAll('[data-goto]').forEach(button=>button.addEventListener('click',()=>page(button.dataset.goto)));
$('refresh').addEventListener('click',()=>refresh().then(()=>toast('已刷新')).catch(e=>toast(e.message,true)));
for(const id of ['hero-import','open-import'])$(id).addEventListener('click',()=>{$('import-error').textContent='';$('import-dialog').showModal()});
document.querySelectorAll('.close-dialog').forEach(button=>button.addEventListener('click',()=>{button.closest('dialog').close();if(button.closest('dialog').id==='key-dialog')$('new-key-value').value=''}));
$('import-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;if(file.size>3*1024*1024){toast('文件请控制在 3 MiB 内',true);return}$('import-content').value=await file.text()});
$('import-form').addEventListener('submit',async e=>{e.preventDefault();$('import-error').textContent='';$('import-submit').disabled=true;try{const result=await api('/admin/accounts/import',{method:'POST',body:JSON.stringify({content:$('import-content').value})});$('import-content').value='';$('import-file').value='';$('import-dialog').close();page('accounts');await refresh();toast(`新增 ${result.added} 个，更新 ${result.updated} 个账号`)}catch(err){$('import-error').textContent=err.message}finally{$('import-submit').disabled=false}});
$('account-rows').addEventListener('click',async e=>{const button=e.target.closest('[data-action]');if(!button)return;const {action,id,enabled}=button.dataset;if(action==='delete'&&!confirm('删除这个账号及其登录材料？'))return;button.disabled=true;try{if(action==='check')await api(`/admin/accounts/${id}/check`,{method:'POST'});if(action==='toggle')await api(`/admin/accounts/${id}`,{method:'PATCH',body:JSON.stringify({enabled:enabled==='true'})});if(action==='delete')await api(`/admin/accounts/${id}`,{method:'DELETE'});await refresh();toast(action==='check'?'账号登录成功':'已更新')}catch(err){toast(err.message,true);refresh().catch(()=>{})}finally{button.disabled=false}});
$('check-all').addEventListener('click',async()=>{const b=$('check-all');b.disabled=true;b.textContent='检查中…';try{const result=await api('/admin/accounts/check',{method:'POST'});await refresh();toast(`通过 ${result.ok} 个，失败 ${result.failed} 个，跳过 ${result.skipped} 个`)}catch(err){toast(err.message,true)}finally{b.disabled=false;b.textContent='检查所有账号'}});
$('new-key').addEventListener('click',async()=>{const name=prompt('为这个 API 密钥命名：','我的应用');if(!name)return;try{const result=await api('/admin/keys',{method:'POST',body:JSON.stringify({name})});$('new-key-value').value=result.key;$('chat-key').value=result.key;sessionStorage.setItem('n2a-api',result.key);$('key-dialog').showModal();await refresh()}catch(err){toast(err.message,true)}});
$('key-rows').addEventListener('click',async e=>{const button=e.target.closest('[data-revoke]');if(!button||!confirm('撤销这个密钥？使用它的应用将无法继续调用。'))return;try{await api('/admin/keys/'+button.dataset.revoke,{method:'DELETE'});await refresh();toast('密钥已撤销')}catch(err){toast(err.message,true)}});
async function copy(text){try{await navigator.clipboard.writeText(text);toast('已复制')}catch{toast('无法自动复制，请手动选择文本',true)}}
$('copy-base').addEventListener('click',()=>copy(location.origin+'/v1'));$('copy-model').addEventListener('click',()=>copy('netease-fox'));$('copy-key').addEventListener('click',()=>copy($('new-key-value').value));
$('question').addEventListener('input',()=>{$('char-count').textContent=Array.from($('question').value).length+' / 200 字'});
$('cancel-chat').addEventListener('click',()=>chatController?.abort());
$('chat-form').addEventListener('submit',async e=>{e.preventDefault();const question=$('question').value.trim();if(!question||Array.from(question).length>200){toast('请输入 1–200 字的问题',true);return}chatController=new AbortController();$('send-chat').disabled=true;$('cancel-chat').hidden=false;$('answer').textContent='';$('answer').classList.remove('muted');$('chat-state').textContent='等待回答';sessionStorage.setItem('n2a-api',$('chat-key').value.trim());try{const streaming=$('stream').checked;const response=await fetch('/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+$('chat-key').value.trim()},body:JSON.stringify({model:'netease-fox',messages:[{role:'user',content:question}],stream:streaming}),signal:chatController.signal});if(!response.ok){const result=await response.json();throw new Error(result.error?.message||'请求失败')}if(streaming){const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';let doneSeen=false;while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const events=buffer.split('\n\n');buffer=events.pop();for(const event of events){for(const line of event.split('\n')){if(!line.startsWith('data: '))continue;const data=line.slice(6);if(data==='[DONE]'){doneSeen=true;continue}const chunk=JSON.parse(data);if(chunk.error)throw new Error(chunk.error.message);$('answer').textContent+=chunk.choices?.[0]?.delta?.content||''}}}if(!doneSeen)throw new Error('连接提前结束，请检查请求记录')}else{const result=await response.json();$('answer').textContent=result.choices[0].message.content}$('chat-state').textContent='已完成'}catch(err){$('chat-state').textContent=err.name==='AbortError'?'已取消':'失败';$('answer').textContent+=(err.name==='AbortError'?'请求已取消':err.message)}finally{$('send-chat').disabled=false;$('cancel-chat').hidden=true;chatController=null;refresh().catch(()=>{})}});
$('chat-key').value=sessionStorage.getItem('n2a-api')||'';
if(admin)show().catch(()=>logout());
